name: "Test Package"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: ./.github/composite/nodejs

      - name: Build Package
        shell: bash
        run: |
          pnpm build

      - name: Publish Package
        shell: bash
        run: |
          pnpm run test
