name: "Test Package"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: ./.github/composite/nodejs
        with:
          version: ${{ matrix.node }}

      - name: Build Package
        shell: bash
        run: |
          pnpm build

      - name: Test Package
        shell: bash
        run: |
          pnpm run test
